### ISSUE TITLE
This doesn't work in my side

### ISSUE THREAD

**Issue by ziv2013** [Palatis/Arduino-Lufa#11]
I have tried your example(DualVirtualSerial) but it doesn't work. 

In the device manager, 2 new COM ports are shown. But I can't receive any data by use serial port utility(one sending and one receiving).

I'm not sure if I have missed any thing.

Thanks a lot.

**Comment by Palatis** [comment]
the example will forward stuff received from one to another, but afaik some serial terminal programs cache inputs until a newline (just hit the enter key to input a newline) is received.

you can try just spit out some debug msg (such as `SerialU1.print("S1 "); SerialU1.println(micros());` to both serial and see if anything happens on the terminal prog.

currently I believe it only supports 8U1 and no error checking.
baudrate is ignored altogether since we're USB CDC...

**Comment by ziv2013** [comment]
Hi ,

Thanks a lot. Could you please tell me what serial terminal program are you use? I'd like to have a try.

And my OS is Windows 10 X64.

**Comment by Palatis** [comment]
I just use whatever serial program that's available.
If I'm working with platform.io, I use platformio-ide-terminal plugin inside Atom.io.
If I'm working with Arduino IDE I just use the built-in serial terminal.
for others I usually use putty.
